create table Products (
	ID int NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Price Money NOT NULL,
	Primary Key(ID)
);

create table Customers (
	ID int NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	CardNumber NVARCHAR(50) Not Null,
	Primary Key (ID)
);

create table Orders(
	ID int NOT NULL,
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Products (ID),
	CustomerID int Not Null Foreign key references Customers(ID)
);

--Inserting 3 values into Customers
INSERT INTO Customers (ID, FirstName, LastName, CardNumber) 
	VALUES (1, 'Jean Luc' , 'Ponty', '5215-1601-3272-0399');
INSERT INTO Customers (ID, FirstName, LastName, CardNumber) 
	VALUES (2, 'Robert' , 'Fripp', '5123-1323-3232-2001');
INSERT INTO Customers (ID, FirstName, LastName, CardNumber) 
	VALUES (3, 'Greg' , 'Lake', '6115-1321-3532-3129');

-- Inserting 3 values into Product
INSERT INTO Products (ID, Name, Price) 
	VALUES (1, 'In The Court of the Crimson King', 12.99);
INSERT INTO Products (ID, Name, Price) 
	VALUES (2, 'Relayer', 15.99);
INSERT INTO Products (ID, Name, Price) 
	VALUES (3, 'Larks Tongue in Aspic', 20.99);

-- Inserting 3 values into Orders
INSERT INTO Orders (ID, ProductID, CustomerID)
	VALUES (1, 1, 1);
INSERT INTO Orders (ID, ProductID, CustomerID)
	VALUES (2, 1, 2);
INSERT INTO Orders (ID, ProductID, CustomerID)
	VALUES (3, 2, 1);

-- Adding Product iPhone
INSERT INTO Products (ID, Name, Price)
		Values(4, 'iPhone', 200.00)

-- Adding Customer Tina Smith
INSERT INTO Customers (ID, FirstName, LastName, CardNumber) 
	VALUES (4, 'Tina' , 'Smith', '3231-4232-3521-4206');

-- Create Order for Tina Smith bough an iPhone
INSERT INTO Orders (ID, ProductID, CustomerID)
	VALUES (4, 4, 4);

-- Reports all orders by Tina Smith
select * from Orders where CustomerID = 4;

--Report all revenue generated by sales of iPhone
select Products.ID, (Sum(Orders.id) * Products.Price) from Orders, Products where Product.ID = 4 AND  Orders.ProductID = 4 group by Product.ID;

--Increase salary of Tina Smith to $90,000
UPDATE Products
	SET Price = 250
	WHERE ID = 4;