-- ASSESSMENT WEEK-2

-- create database
CREATE TABLE Products(
	ID INT NOT NULL IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Price MONEY NOT NULL
);

CREATE TABLE Orders(
	ID INT NOT NULL IDENTITY,
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Products (ID),
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customers (ID)
);

CREATE TABLE Customers(
	ID INT NOT NULL IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,

	-- Assuming that the cardnumber is just a 16 digit credit card number
	CardNumber NVARCHAR(16) NOT NULL
);

-- Add 3 records into each table
INSERT INTO Products (Name, Price) VALUES
	('Samsung Galaxy', 450),
	('Nokia', 10),
	('Toaster', 459);

INSERT INTO Customers (FirstName, LastName, CardNumber) VALUES
	('Robert', 'Downey','1234123412341234'),
	('Gankey','Dankey','4321432143214321'),
	('Theresa','Grupe','0001000100010001');

INSERT INTO Orders (ProductID, CustomerID) VALUES
	(1,1),
	(2,2),
	(3,1);

-- add product iphone at 200$
INSERT INTO Products (Name, Price) VALUES
('iPhone',200)

--add customer tina smith
INSERT INTO Customers (FirstName, LastName) VALUES
('Tina','Smith')

-- add order for iphone for tina smith
DECLARE @tinaID INT
SET @tinaID = ID FROM Customers WHERE FirstName = 'Tina' AND LastName = 'Smith'
DECLARE @iphoneID INT
SET @iphoneID = ID FROM Products WHERE Name = 'iPhone'
INSERT INTO Orders (ProductID, CustomerID) VALUES
	(@iphoneID, @tinaID)


--report all orders by tina smith

DECLARE @tinaID INT
SET @tinaID = ID FROM Customers WHERE FirstName = 'Tina' AND LastName = 'Smith'
SELECT * FROM o.Orders
INNER JOIN c.Customers ON o.CustomerID = c.ID WHERE c.ID = @tinaID


-- report all revenue generated by sales of iPhone
SELECT SUM(Price) FROM p.Products 
CROSS JOIN o.Orders 
ON p.ID = o.ProductID WHERE p.Name = 'iPhone'

-- increase the price of iPhone to 250
UPDATE Products
SET Price = 250
WHERE Name = 'iPhone'