--addd at leadsst 3 records into each table

INSERT INTO Products (Name, Price) VALUES ('iphone',200);
INSERT INTO Products (Name, Price) VALUES ('iphone2',220);
INSERT INTO Products (Name, Price) VALUES ('ophone3',230);

INSERT INTO Orders (ProductID, CustomerID) VALUES (100,1000);
INSERT INTO Orders (ProductID, CustomerID) VALUES (101,1001);
INSERT INTO Orders (ProductID, CustomerID) VALUES (102,1002);

INSERT INTO Customers (FirstName, LastName, CardNumber) VALUES ('Mark','Moore',1000100010001000);
INSERT INTO Customers (FirstName, LastName, CardNumber) VALUES ('Jim','Jones',1100100010001000);
INSERT INTO Customers (FirstName, LastName, CardNumber) VALUES ('Tina','Smith',1200100010001000);




--add product iPhone priced at $200

--see above--


--add customer Tina Smith

--see above--


--create order Tina Smith bought an iPhone

INSERT INTO Orders (ProductID, CustomerID) VALUES (1,3);



--report all orders by Tina Smith

SELECT * FROM Orders
WHERE CustomerID = (SELECT ID FROM Customers WHERE FirstName = 'Tina' AND LastName = 'Smith');


--report all revenue generated by sales of iPhone

SELECT Products.Name, Products.Price, COUNT(DISTINCT ProductID), SUM(products.Price * COUNT(ProductID)) AS TotalRevenue
FROM Products
LEFT JOIN Orders ON Products.ID = Orders.ProductID
GROUP by Orders.ProductID;



--increase price of iPhone to $250

UPDATE Products 
SET Price = 250
WHERE Name = 'iPhone';