drop table EmpDetails;
drop table Employee;
drop table Department;

create table Products(
	ID int identity primary key,
	Name nvarchar(50) not null,
	price int not null
);

create table Customers(
	ID int identity primary key,
	FirstName nvarchar(50) not null,
	LastName nvarchar(50) not null,
	CardNumber int not null
);

create table Orders(
	ID int identity primary key,
	ProductID int foreign key references Products(ID),
	CustomerID int foreign key references Customers(ID) 
);

-- 1. add at least 3 records into each table
insert into Products values
	('product1',100),
	('product2',200),
	('product3',300);

insert into Customers values
	('Sam','Lin','123456'),
	('Tony','Bro','549874'),
	('Domi','John','123789');

insert into Orders values
	(1,1),
	(2,2),
	(3,3);

--2. add product iPhone priced at $200
insert into Products values
	('iPhone',200);

--3. add customer Tina Smith
insert into Customers values
	('Tina','Smith','621726');

--4. creat order for Tina Smith bought an iPhone
insert into Orders values
	(4,4);

--5. report all orders by Tina Smith
select * 
from Orders as o
where o.customerID = 4;

--6. report all revenue generated by sales of iPhone
select Sum(price) as [Total price]
from Products as p
	right join Orders as o on p.ID = o.ProductID
where p.ID = 4;

--7. incease the price of iPhone to $250
update Products
set price = 250
where ID = 4;

--
select * from products;

update Products
set price = 200
where ID = 4;