-- CREATE Database

-- DROP all previous tables
DROP TABLE Orders;
DROP TABLE Customers;
DROP TABLE Products;

-- CREATE TABLE Products
CREATE TABLE Products (
	ID INT IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	Price MONEY NOT NULL,
	CONSTRAINT PK_Products PRIMARY KEY (ID),
	CONSTRAINT CHK_Price_Nonnegative CHECK (Price > 0)
);

-- CREATE TABLE Customers
CREATE TABLE Customers (
	ID INT IDENTITY(1,1),
	Firstname NVARCHAR(255) NOT NULL,
	Lastname NVARCHAR(255) NOT NULL,
	CardNumber NVARCHAR(255) NOT NULL,
	CONSTRAINT PK_Customers PRIMARY KEY (ID)
);

-- CREATE TABLE Orders
CREATE TABLE Orders (
	ID INT IDENTITY(1,1),
	ProductID INT NOT NULL,
	CustomerID INT NOT NULL,
	CONSTRAINT PK_Orders PRIMARY KEY (ID),
	CONSTRAINT FK_Orders_Products_ID FOREIGN KEY (ProductID) REFERENCES Products(ID),
	CONSTRAINT FK_Orders_Customers_ID FOREIGN KEY (CustomerID) REFERENCES Customers(ID)
);

-- INSERT INTO 3 Products
INSERT INTO Products (Name, Price) VALUES
	('Butterscotch', 6.32),
	('Dark Chocolate Peppermint', 21.98),
	('White Winter Chai', 16.42);

-- INSERT INTO 3 Orders
INSERT INTO Orders (ProductID, CustomerID) VALUES
	(2, 1),
	(3, 2),
	(1, 3);

-- INSERT INTO 3 Customers
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES
	('Henry', 'Ford', '98738561984728969'),
	('Nikola', 'Tesla', '23645235635665232'),
	('George', 'Washington', '73656372514711884');

-- INSERT INTO Product iPhone at $200
INSERT INTO Products (Name, Price) VALUES
	('iPhone', 200.00);

-- INSERT INTO Customer Tina Smith
INSERT INTO Customers (Firstname, Lastname, CardNumber) VALUES
	('Tina', 'Smith', '87456776673675376');

-- INSERT INTO Order for Tina Smith for iPhone
INSERT INTO Orders (ProductID, CustomerID) VALUES
	(4, 4);

-- SELECT Orders by Tina Smith
SELECT o.*
FROM Orders o
JOIN Customers c
ON o.CustomerID = c.ID
WHERE c.Firstname = 'Tina' AND c.Lastname = 'Smith';

-- Report all revenue generated by sales of iPhone
-- SUM(Price) of iPhone in ORDERS
SELECT SUM(p.Price)
FROM Orders o
JOIN Products p
ON o.ProductID = p.ID
WHERE p.Name = 'iPhone';

-- UPDATE iPhone price to $250
UPDATE Products
SET Price = 250.00
WHERE Name = 'iPhone';