-- CREATE Database

-- CREATE TABLE Products

-- CREATE TABLE Orders

-- CREATE TABLE Customers

-- INSERT INTO 3 Products

-- INSERT INTO 3 Orders

-- INSERT INTO 3 Customers

-- INSERT INTO Product iPhone at $200

-- INSERT INTO Customer Tina Smith

-- INSERT INTO Order for Tina Smith for iPhone

-- SELECT Orders by Tina Smith

-- Report all revenue generated by sales of iPhone
-- SUM(Price) of iPhone in ORDERS

-- UPDATE iPhone price to $250