/** Create tables **/

--CREATE TABLE [dbo].[Products]
--(
--    [ProductsId] INT NOT NULL,
--    [Name] NVARCHAR(160) NOT NULL,
--    [Price] INT NOT NULL,
--    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([ProductsId])
--);

--CREATE TABLE [dbo].[Orders]
--(
--    [OrdersId] INT NOT NULL,
--    [ProductsId] INT NOT NULL,
--    [CustomerId] INT NOT NULL,
--    CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([OrdersId])
--);

--CREATE TABLE [dbo].[Customers]
--(
--    [CustomersId] INT NOT NULL,
--    [Firstname] NVARCHAR(60) NOT NULL,
--    [Lastname] NVARCHAR(60) NOT NULL,
--	[CardNumber] INT NOT NULL,
--    CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CustomersId])
--);

/** Create foreign keys **/

--ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [FK_OrderProductId]
--    FOREIGN KEY ([ProductsId]) REFERENCES [dbo].[Products] ([ProductsId]) ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO
--ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [FK_OrderCustomerId]
--    FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([CustomersId]) ON DELETE NO ACTION ON UPDATE NO ACTION;
--GO

/** Create queries **/

--add at least 3 records into each table
INSERT INTO Products (ProductsId,Name, Price) VALUES (1, 'Note9+', 900);
INSERT INTO Products (ProductsId,Name, Price) VALUES (2, 'Galaxy s8', 500);
INSERT INTO Products (ProductsId,Name, Price) VALUES (3, 'Note9', 800);

INSERT INTO Customers (CustomersId, Firstname, Lastname, CardNumber) 
VALUES (1,'Aces', 'Loco', 0001);

INSERT INTO Orders (OrdersId, ProductsId, CustomerId) VALUES (1, 1, 1);
INSERT INTO Orders (OrdersId, ProductsId, CustomerId) VALUES (2, 3, 2);
INSERT INTO Orders (OrdersId, ProductsId, CustomerId) VALUES (3, 2, 3);




-- add product iPhone priced at $200.
-- add customer Tina Smith.
-- create order for Tina Smith bought an IPhone.
-- report all orders by Tina Smith.
-- report all revenue generated by sales of IPhone.
-- increase the price of IPhone to $250.

